package instagramTP;


public class PostPanel extends javax.swing.JPanel {

    /**
     * Creates new form PostPane
     */
    public PostPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        idLabel = new javax.swing.JLabel();
        moreBtn = new javax.swing.JButton();
        imagePane = new javax.swing.JPanel();
        likePane = new javax.swing.JPanel();
        likeBtn = new javax.swing.JButton();
        likeNumLabel = new javax.swing.JLabel();
        createdAtLabel = new javax.swing.JLabel();
        postTextArea = new javax.swing.JTextArea();
        commentPane = new javax.swing.JPanel();
        commentWindowBtn = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        postCommentBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        idLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        idLabel.setText("recyan__");

        moreBtn.setBackground(null);
        moreBtn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        moreBtn.setText("...");
        moreBtn.setBorder(null);

        imagePane.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout imagePaneLayout = new javax.swing.GroupLayout(imagePane);
        imagePane.setLayout(imagePaneLayout);
        imagePaneLayout.setHorizontalGroup(
            imagePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        imagePaneLayout.setVerticalGroup(
            imagePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 314, Short.MAX_VALUE)
        );

        likePane.setBackground(null);
        likePane.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 12, 0, 12));
        likePane.setLayout(new java.awt.BorderLayout());

        likeBtn.setBackground(null);
        likeBtn.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        likeBtn.setText("하트");
        likeBtn.setBorder(null);
        likePane.add(likeBtn, java.awt.BorderLayout.CENTER);

        likeNumLabel.setText("nnn people liked");
        likePane.add(likeNumLabel, java.awt.BorderLayout.EAST);

        createdAtLabel.setText("21시간 전");
        likePane.add(createdAtLabel, java.awt.BorderLayout.WEST);

        postTextArea.setEditable(false);
        postTextArea.setBackground(null);
        postTextArea.setColumns(20);
        postTextArea.setRows(5);
        postTextArea.setText("글내용 글내용 글내용 ~ \n글내용!\n");
        postTextArea.setBorder(javax.swing.BorderFactory.createEmptyBorder(12, 12, 12, 12));

        commentPane.setBackground(null);

        commentWindowBtn.setBackground(null);
        commentWindowBtn.setText("댓");

        jTextField1.setText("leave a comment...");

        postCommentBtn.setBackground(null);
        postCommentBtn.setText("comment");

        javax.swing.GroupLayout commentPaneLayout = new javax.swing.GroupLayout(commentPane);
        commentPane.setLayout(commentPaneLayout);
        commentPaneLayout.setHorizontalGroup(
            commentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(commentPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(commentWindowBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(postCommentBtn)
                .addContainerGap())
        );
        commentPaneLayout.setVerticalGroup(
            commentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(commentPaneLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(commentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(commentWindowBtn)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(postCommentBtn))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(idLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(moreBtn)
                .addGap(12, 12, 12))
            .addComponent(imagePane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(likePane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(postTextArea)
            .addComponent(commentPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLabel)
                    .addComponent(moreBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imagePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(likePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(postTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(commentPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>                        


    // Variables declaration - do not modify                     
    private javax.swing.JPanel commentPane;
    private javax.swing.JButton commentWindowBtn;
    private javax.swing.JLabel createdAtLabel;
    private javax.swing.JLabel idLabel;
    private javax.swing.JPanel imagePane;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton likeBtn;
    private javax.swing.JLabel likeNumLabel;
    private javax.swing.JPanel likePane;
    private javax.swing.JButton moreBtn;
    private javax.swing.JButton postCommentBtn;
    private javax.swing.JTextArea postTextArea;
    // End of variables declaration                   
}
